app:
  mysql:
    login:
      enabled: true
      url: root:rafo123@(127.0.0.1:3306)/mj_login?charset=utf8&parseTime=true&loc=Asia%2FShanghai
      maxIdleConnection: 100
      maxOpenConnection: 130
      connMaxLifetime: 100
    gm:
      enabled: true
      url: root:rafo123@(127.0.0.1:3306)/mj_gm?charset=utf8&parseTime=true&loc=Asia%2FShanghai
      maxIdleConnection: 100
      maxOpenConnection: 130
      connMaxLifetime: 100
    hall:
      enabled: true
      url: root:rafo123@(127.0.0.1:3306)/mj_hall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
      maxIdleConnection: 100
      maxOpenConnection: 130
      connMaxLifetime: 100