// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth/auth.proto

package zhj_micro_admin_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Auth service

func NewAuthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Auth service

type AuthService interface {
	CreateAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	DelAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	RefreshAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	ValidAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) CreateAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.CreateAccessToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) DelAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.DelAccessToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) RefreshAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.RefreshAccessToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) ValidAccessToken(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Auth.ValidAccessToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	CreateAccessToken(context.Context, *Request, *Response) error
	DelAccessToken(context.Context, *Request, *Response) error
	RefreshAccessToken(context.Context, *Request, *Response) error
	ValidAccessToken(context.Context, *Request, *Response) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		CreateAccessToken(ctx context.Context, in *Request, out *Response) error
		DelAccessToken(ctx context.Context, in *Request, out *Response) error
		RefreshAccessToken(ctx context.Context, in *Request, out *Response) error
		ValidAccessToken(ctx context.Context, in *Request, out *Response) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) CreateAccessToken(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.CreateAccessToken(ctx, in, out)
}

func (h *authHandler) DelAccessToken(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.DelAccessToken(ctx, in, out)
}

func (h *authHandler) RefreshAccessToken(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.RefreshAccessToken(ctx, in, out)
}

func (h *authHandler) ValidAccessToken(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.ValidAccessToken(ctx, in, out)
}
